"""create reports table

Revision ID: 9ba606d783f0
Revises: 
Create Date: 2026-04-24 18:05:27.624736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba606d783f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('user_note', sa.String(length=1000), nullable=True),
    sa.Column('page_url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('reproduction_steps', sa.Text(), nullable=True),
    sa.Column('expected_behavior', sa.Text(), nullable=False),
    sa.Column('actual_behavior', sa.Text(), nullable=False),
    sa.Column('suspected_area', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###